### ISSUE TITLE
Feature request: web server

### ISSUE THREAD

**Issue by h1aji** [pisicaverde/yet-another-internet-radio#3]
Do you have any plans to implement Web server interface? Similar to Ka-Radio project
There are examples on LUA.
Would be nice and hand if there would be control API also.

**Comment by pisicaverde** [comment]
I don't have any intentions for it, since I've thought it as a "desktop" radio...

I'm planning to replace WifiManager with a web-based config page, for editing stations with a visual interface, edit wifi settings etc (updating NTP and downloading station list takes most of the startup time). Coming in spring-summer 2019 :)
